import { Inter } from "next/font/google";

import Footer from "~/app/components/footer";
import Header from "~/app/components/header";
import { TRPCReactProvider } from "~/trpc/react";

import "~/styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Task Manager",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={`flex flex-col h-screen max-h-screen font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <Header />
            {children}
            <Footer />
          </TRPCReactProvider>
        </body>
    </html>
  );
}
